{
 "title": "MongoDB",
 "description": "Note for a official Grafana MongoDB plugin, please view:\nhttps://grafana.com/grafana/plugins/grafana-mongodb-datasource\n\nThis is a MongoDB Prometheus Exporter Dashboard. \nWorks well with https://github.com/dcu/mongodb_exporter\n\nIf you have the node_exporter running on the mongo instance, you will also get some useful alert panels related to disk io and cpu.",
 "tags": [ "prometheus" ],
 "time": { "from": "now/d", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "env",
    "label": "env",
    "query": {
     "query": "mongodb_up{namespace=\"$namespace\"}"
    }
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "namespace", "query": { "query": "mongodb_up" } }
  ]
 },
 "panels": [
  {
   "title": "Health metrics for $env",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "env",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 1 },
     "options": {
      "content": "# <p style=\"text-align:center;\">Health Metrics</p>"
     }
    },
    {
     "title": "Uptime",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "mongodb_instance_uptime_seconds{pod=~\"$env\"}"
      }
     ]
    },
    {
     "title": "Available Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 4, "x": 4, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{pod=~\"$env\",state=\"available\"}"
      }
     ]
    },
    {
     "title": "Open Connections",
     "type": "stat",
     "gridPos": { "h": 4, "w": 16, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "mongodb_connections{pod=~\"$env\",state=\"current\"}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 7 },
     "options": {
      "content": "# <p style=\"text-align:center;\">Document Operations Metrics</p>"
     }
    },
    {
     "title": "Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 9, "x": 0, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_op_counters_total{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Document Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 9, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_metrics_document{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Document Query Executor",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 7, "x": 17, "y": 9 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_metrics_query_executor_total{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 15 },
     "options": {
      "content": "# <p style=\"text-align:center;\">Network I/O Metrics</p>"
     }
    },
    {
     "title": "Bytes In",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 11, "x": 0, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_network_bytesIn{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{state}}"
      }
     ]
    },
    {
     "title": "Bytes Out",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 13, "x": 11, "y": 17 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "rate(mongodb_ss_network_bytesOut{pod=~\"$env\"}[$interval])",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 23 },
     "options": {
      "content": "# <p style=\"text-align:center;\">ReplicaSet Metrics</p>"
     }
    },
    {
     "title": "Member Health",
     "type": "barchart",
     "gridPos": { "h": 6, "w": 6, "x": 0, "y": 25 },
     "targets": [
      {
       "expr": "mongodb_mongod_replset_number_of_members{pod=~\"$env\"}",
       "legendFormat": "# members"
      },
      {
       "expr": "sum(mongodb_members_health{pod=~\"$env\"})",
       "legendFormat": "healthy members"
      }
     ]
    },
    {
     "title": "Member State",
     "type": "table",
     "description": "See which node is currently acting as the primary, secondary, ...",
     "gridPos": { "h": 6, "w": 12, "x": 6, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "mongodb_rs_members_state{pod=~\"$env\"}",
       "legendFormat": "{{state}} - {{name}}"
      }
     ]
    },
    {
     "title": "Replica Query Operations",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 6, "x": 18, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "ops" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_op_counters_repl_total{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "type": "text",
     "gridPos": { "h": 2, "w": 24, "x": 0, "y": 31 },
     "options": {
      "content": "# <p style=\"text-align:center;\">Resource Usage Metrics</p>"
     }
    },
    {
     "title": "Oplog Size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decgbytes" } },
     "targets": [
      {
       "expr": "rate(mongodb_oplog_stats_storageStats_size{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{type}}"
      }
     ]
    },
    {
     "title": "Oplog Lag",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 8, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "rate(mongodb_mongod_replset_oplog_head_timestamp{pod=~\"$env\"}[$interval])",
       "legendFormat": "{{instance}}"
      }
     ]
    },
    {
     "title": "Memory",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 8, "x": 16, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "decmbytes" } },
     "targets": [
      {
       "expr": "mongodb_memory{pod=~\"$env\",type=~\"resident|virtual\"}",
       "legendFormat": "{{type}}"
      }
     ]
    }
   ]
  }
 ]
}